### ISSUE TITLE
Underscore source name conflicts with NeoBundle lazy loading

### ISSUE THREAD

**Issue by languitar** [kopischke/unite-spell-suggest#17]
I have remapped `z=` to `:Unite spell_suggest`. This worked well until a few weeks ago. I am not sure whether Unite itself changed or this source, but now, calling `z=` results in:

```
[unite.vim] Invalid source name "spell_suggest" is detected.                                                                                                                                                                                   
[unite.vim] unite.vim: Invalid source
```

I am using this mapping:

```
nmap z= :Unite spell_suggest <CR>
```

**Comment by kopischke** [comment]
That sounds as if Unite doesn't find the source at all. Does a plain `:Unite spell_suggest` at the command line work at all?

**Comment by languitar** [comment]
Yes, it is also listed in the interactive menu.

**Comment by kopischke** [comment]
Have you tried `nnoremap z= :Unite spell_suggest <CR>`?

**Comment by languitar** [comment]
Both suggestions do not help.

But I just found something strange: When I open up vim and type `:Unite spell<TAB>`, I get a completion for `:Unite spell-suggest`. This one ens up in the same error message as above.

Afterwards, completing the same `spell` prefix results in `spell_suggest` (underscore) and works. Lazy loading or something like that?

**Comment by kopischke** [comment]
Are you using `NeoBundle` and it's built-in support for lazy loading Unite sources, by any chance?

**Comment by languitar** [comment]
Yes, I am using neobundle. I have nothing specific configured for lazy-loading though.

**Comment by kopischke** [comment]
NeoBundle automatically sets the lazy load key `on_unite` for bundles whose names starts with “unite”, using the rest of the bundle name as the source name (see `:h neobundle-options-on_unite`), which would explain the confusion … try changing your NeoBundle command to:

```vim
NeoBundle kopischke/unite-spell-suggest { 'on_unite': 'spell_suggest' }
```

then restarting Vim and see if that helps. If that is the issue, I will see that I solve this more permanently.

**Comment by languitar** [comment]
Ah, yes that helps. Maybe it would be good to add this to the readme

**Comment by kopischke** [comment]
Actually, I have been itching to rename that source for a while – the underscore name is something I inherited from upstream and that I am not terribly fond of – and this sounds like a good rationale for it. The only issue is maintaining backwards compatibility without duplicating the code, but I have some ideas about that

**Comment by kopischke** [comment]
This plugin is officially EOL as I no longer use Vim (much), much less Unite. Sorry.
