### ISSUE TITLE
Denite support

### ISSUE THREAD

**Issue by petobens** [kopischke/unite-spell-suggest#18]
Hi @kopischke,  is there any plan to add support for [denite.nvim](https://github.com/Shougo/denite.nvim)? Thanks!

**Comment by kopischke** [comment]
I am sorry to say that is rather unlikely, as the plugin is effectively unmaintained for a simple reason: I have stopped using Unite. However, I am curious as to how Denite compares to Unite in practice (all I know is that it is a rewrite leveraging Neovim’ async feature).

**Comment by kopischke** [comment]
This plugin is officially EOL as I no longer use Vim (much), much less Unite. Sorry.
